-- Zachry Insurance website security + testimonial workflow
-- Run this once in Supabase Dashboard -> SQL Editor.
-- Review the statements before running them in production.

begin;

-- ---------------------------------------------------------
-- EXISTING WEBSITE FORM TABLES
-- Visitors may INSERT form submissions but may not read,
-- update, or delete records through the public browser key.
-- ---------------------------------------------------------

alter table if exists public.leads enable row level security;
alter table if exists public.recruiting_leads enable row level security;
alter table if exists public.agent_applications enable row level security;

revoke select, update, delete on table public.leads from anon, authenticated;
revoke select, update, delete on table public.recruiting_leads from anon, authenticated;
revoke select, update, delete on table public.agent_applications from anon, authenticated;

grant insert on table public.leads to anon, authenticated;
grant insert on table public.recruiting_leads to anon, authenticated;
grant insert on table public.agent_applications to anon, authenticated;

drop policy if exists "website visitors can submit leads" on public.leads;
create policy "website visitors can submit leads"
on public.leads
for insert
to anon, authenticated
with check (true);

drop policy if exists "website visitors can submit recruiting leads" on public.recruiting_leads;
create policy "website visitors can submit recruiting leads"
on public.recruiting_leads
for insert
to anon, authenticated
with check (true);

drop policy if exists "website visitors can submit agent applications" on public.agent_applications;
create policy "website visitors can submit agent applications"
on public.agent_applications
for insert
to anon, authenticated
with check (true);

-- ---------------------------------------------------------
-- TESTIMONIALS
-- Public visitors can submit PENDING testimonials only.
-- Public visitors can read ONLY APPROVED testimonials and
-- only the columns granted below. Email and permission data
-- remain private from the public browser key.
-- ---------------------------------------------------------

create table if not exists public.testimonials (
    id bigint generated by default as identity primary key,
    display_name text not null check (char_length(display_name) between 1 and 100),
    email text not null check (char_length(email) between 3 and 150),
    testimonial text not null check (char_length(testimonial) between 1 and 1500),
    permission_to_publish boolean not null default false,
    permission_text text not null,
    permission_recorded_at timestamptz not null default now(),
    source_page text,
    status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
    submitted_at timestamptz not null default now(),
    approved_at timestamptz
);

alter table public.testimonials enable row level security;

revoke all on table public.testimonials from anon, authenticated;
grant insert on table public.testimonials to anon, authenticated;
grant select (id, display_name, testimonial, approved_at) on table public.testimonials to anon, authenticated;

-- Identity columns may use this sequence when inserting.
do $$
declare
    seq_name text;
begin
    select pg_get_serial_sequence('public.testimonials', 'id') into seq_name;
    if seq_name is not null then
        execute format('grant usage, select on sequence %s to anon, authenticated', seq_name);
    end if;
end $$;

drop policy if exists "website visitors can submit pending testimonials" on public.testimonials;
create policy "website visitors can submit pending testimonials"
on public.testimonials
for insert
to anon, authenticated
with check (
    status = 'pending'
    and approved_at is null
    and permission_to_publish = true
);

drop policy if exists "public can read approved testimonials" on public.testimonials;
create policy "public can read approved testimonials"
on public.testimonials
for select
to anon, authenticated
using (
    status = 'approved'
    and permission_to_publish = true
);

-- Automatically timestamp approval when Clay changes status to approved
-- in the Supabase Table Editor.
create or replace function public.set_testimonial_approved_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
    if new.status = 'approved' and old.status is distinct from 'approved' then
        new.approved_at = now();
    elsif new.status <> 'approved' then
        new.approved_at = null;
    end if;
    return new;
end;
$$;

drop trigger if exists testimonials_set_approved_at on public.testimonials;
create trigger testimonials_set_approved_at
before update on public.testimonials
for each row
execute function public.set_testimonial_approved_at();

commit;

-- HOW CLAY APPROVES A TESTIMONIAL:
-- 1. Supabase Dashboard -> Table Editor -> testimonials
-- 2. Open the pending row and read the testimonial.
-- 3. Change status from pending to approved.
-- 4. Save. The approved_at timestamp is added automatically.
-- 5. The testimonial will automatically appear on the homepage.
--
-- To hide it later, change status to rejected or pending.
